# A workflow that builds and deploys the HackUTD website to GitHub Pages.

name: CI

# Controls when the action will run. Triggers the workflow on push events but
# only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run deploy
      env:
        CI: true